require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-rspec_rails
  - rubocop-graphql

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
